xP-xD/bunsanedThinking_Front

- js/utils/TimeStampFormatter.js
- js/utils/apiUtils/apiDocumentation/customer/customer.js
- js/utils/apiUtils/apiHandler/FetchHandler.js
- js/utils/apiUtils/apiHandler/customer/customer.js
+TimeStampFormatter까지 올렸는데 그건 파일 주석 참고하십셔
> [추가] FetchHandler를 넣어봤심다

- config/constants.js
- js/utils/uiUtils/buttonManager/customer/customer.js
- js/utils/uiUtils/messageManager/customer/customer.js
> Customer 예시 코드(실제로도 맞음) 추가

- js/utils/apiUtils/apiDocumentation/employee/administrative/administrative.js
- js/utils/apiUtils/apiDocumentation/employee/customerInformationManagement/customerInformationManagement.js
- js/utils/apiUtils/apiDocumentation/employee/managementPlanning/managementPlanning.js
- js/utils/apiUtils/apiDocumentation/partnerCompany/partnerCompany.js
- js/utils/apiUtils/apiHandler/employee/administrative/administrative.js
- js/utils/apiUtils/apiHandler/employee/customerInformationManagement/customerInformationManagement.js
- js/utils/apiUtils/apiHandler/employee/managementPlanning/managementPlanning.js
- js/utils/apiUtils/apiHandler/partnerCompany/partnerCompany.js
> '숙제 완료 - 모'가 가장 최신입니다

- html/customer/informationList.html
- js/utils/uiUtils/buttonManager/customer/customer.js
> customer 창 연구중입니다 - 윰

- js/utils/apiUtils/apiHandler/customer/customer.js
- js/utils/apiUtils/apiHandler/employee/compensation/compensation.js
- js/utils/apiUtils/apiHandler/employee/compensationPlanning/compensationPlanning.js
- js/utils/apiUtils/apiHandler/employee/contractManagement/contractManagement.js
> [FIX] patch가 두개!?!?!?!!

- js/utils/apiUtils/apiDocumentation/employee/administrative/administrative.js
- js/utils/apiUtils/apiDocumentation/partnerCompany/partnerCompany.js
- js/utils/apiUtils/apiHandler/employee/administrative/administrative.js
- js/utils/apiUtils/apiHandler/employee/customerInformationManagement/customerInformationManagement.js
- js/utils/apiUtils/apiHandler/employee/managementPlanning/managementPlanning.js
- js/utils/apiUtils/apiHandler/partnerCompany/partnerCompany.js
PatchHandler를 WIthBody와 WithParams로 나누기
> PatchHandler를 WIthBody와 WithParams로 나누기

- html/customer/customer.html
- html/customer/informationList.html
- js/utils/uiUtils/buttonManager/customer/customer.js
- js/utils/uiUtils/messageManager/customer/customer.js
- js/utils/uiUtils/tableRenderer/customer/customer.js
> 연구 성과를 보여드림

- config/constants.js
- js/utils/uiUtils/buttonManager/customer/customer.js
- js/utils/uiUtils/tableRenderer/customer/customer.js
> [쀸스] 주석 몇개 달아둠

- config/employee/contractManagement/contractManagement.js
- js/utils/uiUtils/tableRenderer/employee/contractManagement/contractManagement.js
Customer, Compensation, ContractManagement, CompensationPlanning까지 모두 완성
> [ADD] 4개 컨트롤러 모두 완성

- js/utils/uiUtils/tableRenderer/employee/underWriting/underWriting.js
> [FIX] 무서워유ㅠㅠㅠㅠㅠㅠㅠ

- js/utils/uiUtils/tableRenderer/customer/customer.js
> [FIX] . 하나 땜에...!!!!!

- config/customer/customer.js
- config/employee/contractManagement/contractManagement.js
- js/utils/apiUtils/apiDocumentation/customer/customer.js
- js/utils/apiUtils/apiDocumentation/employee/compensation/compensation.js
- js/utils/apiUtils/apiDocumentation/employee/compensationPlanning/compensationPlanning.js
- js/utils/apiUtils/apiDocumentation/employee/contractManagement/contractManagement.js
- js/utils/apiUtils/apiHandler/customer/customer.js
- js/utils/apiUtils/apiHandler/employee/compensation/compensation.js
- js/utils/apiUtils/apiHandler/employee/compensationPlanning/compensationPlanning.js
- js/utils/apiUtils/apiHandler/employee/contractManagement/contractManagement.js
- js/utils/uiUtils/tableRenderer/customer/customer.js
- js/utils/uiUtils/tableRenderer/employee/compensation/compensation.js
- js/utils/uiUtils/tableRenderer/employee/compensationPlanning/compensationPlanning.js
- js/utils/uiUtils/tableRenderer/employee/contractManagement/contractManagement.js
> 로그인 빼고는 다했숨다

- html/customer/customer.html
- html/employee/compensation/compensation.html
- html/employee/compensationPlanning/compensationPlanning.html
- html/employee/contractManagement/contractManagement.html
- html/login.html
- js/login.js
- js/utils/apiUtils/apiDocumentation/authentication.js
- js/utils/apiUtils/apiHandler/authentication.js
- js/utils/uiUtils/messageManager/employee/compensation/compensation.js
- js/utils/uiUtils/messageManager/employee/compensationPlanning/compensationPlanning.js
- js/utils/uiUtils/messageManager/employee/contractManagement/contractManagement.js
- js/utils/uiUtils/tableRenderer/customer/customer.js
> [ADD] 로그인 기능까지 완

- js/login.js
> [FIX] 로그 이이ㅣ이이이이이이잉

- config/customer/customer.js
- config/employee/contractManagement/contractManagement.js
- js/utils/apiUtils/apiDocumentation/employee/contractManagement/contractManagement.js
- js/utils/apiUtils/apiHandler/employee/contractManagement/contractManagement.js
- js/utils/uiUtils/buttonManager/customer/home.js
- js/utils/uiUtils/buttonManager/employee/compensation/home.js
- js/utils/uiUtils/buttonManager/employee/compensationPlanning/home.js
- js/utils/uiUtils/buttonManager/employee/contractManagement/home.js
- js/utils/uiUtils/tableRenderer/customer/detail.js
- js/utils/uiUtils/tableRenderer/employee/compensation/detail.js
- js/utils/uiUtils/tableRenderer/employee/compensationPlanning/detail.js
- js/utils/uiUtils/tableRenderer/employee/contractManagement/detail.js
- js/utils/uiUtils/tableRenderer/employee/contractManagement/informationList.js
> 버튼렌더러로 옮겨놨심다

- js/utils/uiUtils/buttonManager/employee/contractManagement/home.js
- js/utils/uiUtils/common/buttonUtils.js
- js/utils/uiUtils/tableRenderer/employee/contractManagement/detail.js
> [FIX] button Util 변경, back()씀

- js/utils/uiUtils/buttonManager/customer/home.js
- js/utils/uiUtils/buttonManager/employee/compensation/home.js
- js/utils/uiUtils/buttonManager/employee/compensationPlanning/home.js
- js/utils/uiUtils/tableRenderer/customer/detail.js
- js/utils/uiUtils/tableRenderer/employee/compensation/detail.js
- js/utils/uiUtils/tableRenderer/employee/compensationPlanning/detail.js
> [FIX] 4개부서 다 옮겨놨심다

- js/utils/uiUtils/tableRenderer/employee/managementPlanning/detail.js
> 부서관리 상세정보 인원수로 수정-모

- html/employee/productManagement/input.html
- js/utils/uiUtils/tableRenderer/employee/productManagement/detail.js
- js/utils/uiUtils/tableRenderer/employee/productManagement/input.js
> [FIX] 입력창 정상화

- js/utils/uiUtils/buttonManager/employee/compensationPlanning/input.js
> [FIX] 오카네 카세구

- config/employee/compensation/compensation.js
- config/employee/compensationPlanning/compensationPlanning.js
- js/utils/uiUtils/buttonManager/employee/compensation/input.js
- js/utils/uiUtils/buttonManager/employee/compensationPlanning/input.js
- js/utils/uiUtils/tableRenderer/customer/informationList.js
> [FIX] exception config 분리, date 받는거 수정

- js/utils/uiUtils/tableRenderer/employee/customerInformationManagement/input.js
고객정보관리에서 등록할 때 각종 이력들 추가하는 항목 삭제 버튼 추가 - 모
> 고객정보관리에서 등록할 때 각종 이력들 추가하는 항목 삭제 버튼 추가 - 모

- config/register.js
- css/input.css
- html/common/register.html
- js/utils/uiUtils/buttonManager/register.js
- js/utils/uiUtils/tableRenderer/customer/input.js
- js/utils/uiUtils/tableRenderer/register.js
> 회원가입 하다 말음

- config/common.js
- html/common/login.html
- js/utils/uiUtils/buttonManager/customer/input.js
- js/utils/uiUtils/buttonManager/employee/compensation/detail.js
- js/utils/uiUtils/buttonManager/employee/compensation/input.js
- js/utils/uiUtils/buttonManager/employee/compensationPlanning/detail.js
- js/utils/uiUtils/buttonManager/employee/compensationPlanning/informationList.js
- js/utils/uiUtils/buttonManager/employee/compensationPlanning/input.js
- js/utils/uiUtils/buttonManager/employee/contractManagement/detail.js
- js/utils/uiUtils/login/login.js
- js/utils/uiUtils/tableRenderer/customer/detail.js
- js/utils/uiUtils/tableRenderer/customer/informationList.js
- js/utils/uiUtils/tableRenderer/employee/compensation/detail.js
- js/utils/uiUtils/tableRenderer/employee/compensation/informationList.js
- js/utils/uiUtils/tableRenderer/employee/compensation/input.js
- js/utils/uiUtils/tableRenderer/employee/compensationPlanning/detail.js
- js/utils/uiUtils/tableRenderer/employee/compensationPlanning/informationList.js
- js/utils/uiUtils/tableRenderer/employee/compensationPlanning/input.js
- js/utils/uiUtils/tableRenderer/employee/contractManagement/detail.js
- js/utils/uiUtils/tableRenderer/employee/contractManagement/informationList.js
> [FIX] 로그인 id 수정

- css/input.css
- js/utils/apiUtils/apiDocumentation/employee/customerInformationManagement/customerInformationManagement.js
- js/utils/uiUtils/buttonManager/employee/customerInformationManagement/input.js
- js/utils/uiUtils/tableRenderer/employee/customerInformationManagement/input.js
> 고객정보에서 이력 수정

- config/customer/customer.js
- config/register.js
- js/utils/uiUtils/buttonManager/customer/input.js
- js/utils/uiUtils/tableRenderer/customer/informationList.js
- js/utils/uiUtils/tableRenderer/customer/input.js
- js/utils/uiUtils/tableRenderer/register.js
> [FIX] config 일부 수정, 보험금 신청 구현중

- config/employee/administrative/administrative.js
- config/employee/customerInformationManagement/customerInformationManagement.js
- js/utils/uiUtils/buttonManager/employee/administrative/input.js
- js/utils/uiUtils/buttonManager/employee/customerInformationManagement/input.js
- js/utils/uiUtils/buttonManager/employee/managementPlanning/input.js
- js/utils/uiUtils/buttonManager/partnerCompany/input.js
- js/utils/uiUtils/tableRenderer/employee/administrative/detail.js
- js/utils/uiUtils/tableRenderer/employee/administrative/informationList.js
- js/utils/uiUtils/tableRenderer/employee/administrative/input.js
- js/utils/uiUtils/tableRenderer/employee/customerInformationManagement/detail.js
- js/utils/uiUtils/tableRenderer/employee/customerInformationManagement/informationList.js
- js/utils/uiUtils/tableRenderer/employee/customerInformationManagement/input.js
- js/utils/uiUtils/tableRenderer/employee/managementPlanning/detail.js
모달 창 없애고, administrative, customerInformationManagement 변경 - 모
> 모달 창 없애고, administrative, customerInformationManagement 변경 - 모

- config/employee/customerInformationManagement/customerInformationManagement.js
- html/employee/administrative/home.html
- html/employee/administrative/input.html
- html/employee/customerInformationManagement/input.html
- js/utils/apiUtils/apiDocumentation/employee/managementPlanning/managementPlanning.js
- js/utils/apiUtils/apiHandler/employee/managementPlanning/managementPlanning.js
- js/utils/uiUtils/buttonManager/employee/administrative/home.js
- js/utils/uiUtils/buttonManager/employee/customerInformationManagement/home.js
- js/utils/uiUtils/buttonManager/employee/customerInformationManagement/input.js
- js/utils/uiUtils/buttonManager/partnerCompany/home.js
- js/utils/uiUtils/buttonManager/partnerCompany/input.js
- js/utils/uiUtils/messageManager/employee/administrative/message.js
- js/utils/uiUtils/messageManager/employee/customerInformationManagement/message.js
- js/utils/uiUtils/messageManager/employee/managementPlanning/message.js
- js/utils/uiUtils/tableRenderer/employee/administrative/informationList.js
- js/utils/uiUtils/tableRenderer/employee/administrative/input.js
- js/utils/uiUtils/tableRenderer/employee/customerInformationManagement/detail.js
- js/utils/uiUtils/tableRenderer/employee/customerInformationManagement/informationList.js
- js/utils/uiUtils/tableRenderer/employee/customerInformationManagement/input.js
- js/utils/uiUtils/tableRenderer/employee/managementPlanning/detail.js
- js/utils/uiUtils/tableRenderer/employee/managementPlanning/informationList.js
- js/utils/uiUtils/tableRenderer/employee/managementPlanning/input.js
- js/utils/uiUtils/tableRenderer/partnerCompany/detail.js
- js/utils/uiUtils/tableRenderer/partnerCompany/informationList.js
- js/utils/uiUtils/tableRenderer/partnerCompany/input.js
일단 각 부서의 html있는 부분 빼고 변경함 그리고 모르는 부분도 일단은 내비둠
> 일단 각 부서의 html있는 부분 빼고 변경함 그리고 모르는 부분도 일단은 내비둠

- config/customer/customer.js
- js/utils/apiUtils/apiHandler/customer/customer.js
- js/utils/apiUtils/common/fetchHandler.js
- js/utils/uiUtils/buttonManager/customer/input.js
> [ADD] 사진 첨부 후 서버 전달까지 완

- config/employee/administrative/administrative.js
- config/employee/customerInformationManagement/customerInformationManagement.js
- config/employee/managementPlanning/managementPlanning.js
- config/partnerCompany/partnerCompany.js
- js/utils/uiUtils/buttonManager/employee/administrative/input.js
- js/utils/uiUtils/buttonManager/employee/customerInformationManagement/input.js
- js/utils/uiUtils/buttonManager/partnerCompany/home.js
- js/utils/uiUtils/messageManager/employee/administrative/message.js
- js/utils/uiUtils/messageManager/partnerCompany/message.js
- js/utils/uiUtils/tableRenderer/employee/administrative/informationList.js
- js/utils/uiUtils/tableRenderer/employee/administrative/input.js
- js/utils/uiUtils/tableRenderer/employee/customerInformationManagement/detail.js
- js/utils/uiUtils/tableRenderer/employee/customerInformationManagement/input.js
- js/utils/uiUtils/tableRenderer/employee/managementPlanning/detail.js
- js/utils/uiUtils/tableRenderer/employee/managementPlanning/informationList.js
- js/utils/uiUtils/tableRenderer/employee/managementPlanning/input.js
- js/utils/uiUtils/tableRenderer/partnerCompany/detail.js
- js/utils/uiUtils/tableRenderer/partnerCompany/informationList.js
- js/utils/uiUtils/tableRenderer/partnerCompany/input.js
> 일단 최대한 큰따음표없앰 아마도 다한듯? - 모

- config/employee/administrative/administrative.js
- js/utils/uiUtils/buttonManager/employee/administrative/input.js
- js/utils/uiUtils/tableRenderer/employee/customerInformationManagement/detail.js
- js/utils/uiUtils/tableRenderer/employee/customerInformationManagement/input.js
FEMALE, MALE을 여자, 남자로 한글 변환 - 모
> FEMALE, MALE을 여자, 남자로 한글 변환 - 모

- js/utils/uiUtils/buttonManager/employee/customerInformationManagement/input.js
> config에 있는거 나머지 변경 - 모

- config/customer/customer.js
- js/utils/apiUtils/apiDocumentation/customer/customer.js
- js/utils/apiUtils/apiHandler/customer/customer.js
- js/utils/uiUtils/buttonManager/customer/detail.js
- js/utils/uiUtils/common/buttonUtils.js
> [FIX] 보험금신청 에러 해결

- js/utils/uiUtils/tableRenderer/employee/customerInformationManagement/input.js
겹치는거 수정 - 모(customerInformationManagement에서 수정할 떄 겹치는 오류)
> 겹치는거 수정 - 모

- js/utils/apiUtils/apiHandler/common/common.js
- js/utils/apiUtils/apiHandler/customer/customer.js
- js/utils/apiUtils/apiHandler/employee/administrative/administrative.js
- js/utils/apiUtils/apiHandler/employee/compensation/compensation.js
- js/utils/apiUtils/apiHandler/employee/compensationPlanning/compensationPlanning.js
- js/utils/apiUtils/apiHandler/employee/contractManagement/contractManagement.js
- js/utils/apiUtils/apiHandler/employee/customerInformationManagement/customerInformationManagement.js
- js/utils/apiUtils/apiHandler/employee/customerSupport/customerSupport.js
- js/utils/apiUtils/apiHandler/employee/financialAccountant/financialAccountant.js
- js/utils/apiUtils/apiHandler/employee/humanResource/humanResource.js
- js/utils/apiUtils/apiHandler/employee/loanManagement/loanManagement.js
- js/utils/apiUtils/apiHandler/employee/managementPlanning/managementPlanning.js
- js/utils/apiUtils/apiHandler/employee/productManagement/productManagement.js
- js/utils/apiUtils/apiHandler/employee/sales/sales.js
- js/utils/apiUtils/apiHandler/employee/underWriting/underWriting.js
- js/utils/apiUtils/apiHandler/partnerCompany/partnerCompany.js
> [FIX] 호스트 파일 수정

- js/utils/uiUtils/buttonManager/employee/administrative/input.js
- js/utils/uiUtils/buttonManager/employee/customerInformationManagement/input.js
- js/utils/uiUtils/buttonManager/employee/managementPlanning/input.js
- js/utils/uiUtils/buttonManager/partnerCompany/input.js
이상하게 입력했는데 에러메시도 뜨고 등록되었다는 메시지까지 뜨는거 해결- 모
> 이상하게 입력했는데 에러메시도 뜨고 등록되었다는 메시지까지 뜨는거 해결- 모

- js/utils/uiUtils/tableRenderer/employee/customerInformationManagement/detail.js
- js/utils/uiUtils/tableRenderer/employee/customerInformationManagement/input.js
> [FIX] 지환님 부분 좀 수정

- js/utils/apiUtils/common/authentication.js
> [FIX] defaultURL 적용
